"""
.. module:: ondalear.backend.docmgmt.models.constants
   :synopsis: ondalear backend models constants  module.

The *constants* module contains *server* public constants.

"""

ID_FIELD_MAX_LEGNTH = 64
NAME_FIELD_MAX_LENGTH = 256
TITLE_FIELD_MAX_LENGTH = 256
DESCRIPTION_FIELD_MAX_LENGTH = 2048
CONTENT_TYPE_FIELD_MAX_LENGTH = 32
DIR_PATH_FIELD_MAX_LENGTH = 2048
CONTENT_FIELD_MAX_LENGTH = 1024 * 1024  # 1MB
UPLOAD_FIELD_MAX_FILE_SIZE = 1024 * 1024 * 10   # 10MB
ANNOTATION_FIELD_MAX_LENGTH = 4096

UNKNOWN = 'unknown'
REFERENCE = 'reference'
AUXILIARY = 'auxiliary'
AUXILIARY_DOCUMENT = 'Auxiliary Document'
REFERENCE_DOCUMENT = 'Reference Document'
MIME_TYPE_TEXT = 'text/plain'
MIME_TYPE_UNKNOWN = 'application/octet-stream'

MIME_TYPES = (
    MIME_TYPE_TEXT,
)
MIME_TYPE_CHOICES = (
    (MIME_TYPE_TEXT, 'Plain Text'),
    (MIME_TYPE_UNKNOWN, UNKNOWN.title())
)

CLASSIFICATION_TARGET_REFERENCE_DOCUMENT = REFERENCE
CLASSIFICATION_TARGET_AUXILIARY_DOCUMENT = AUXILIARY
CLASSIFICATION_TARGETS = (
    CLASSIFICATION_TARGET_AUXILIARY_DOCUMENT,
    CLASSIFICATION_TARGET_REFERENCE_DOCUMENT,
)
CLASSIFICATION_TARGET_CHOICES = (
    (CLASSIFICATION_TARGET_AUXILIARY_DOCUMENT, AUXILIARY_DOCUMENT),
    (CLASSIFICATION_TARGET_REFERENCE_DOCUMENT, REFERENCE_DOCUMENT),
)

DOCUMENT_TYPE_REFERENCE = REFERENCE
DOCUMENT_TYPE_AUXILIARY = AUXILIARY
DOCUMENT_TYPE_UNKNOWN = UNKNOWN
DOCUMENT_TYPES = (
    DOCUMENT_TYPE_AUXILIARY,
    DOCUMENT_TYPE_REFERENCE,
    DOCUMENT_TYPE_UNKNOWN,
)
DOCUMENT_TYPE_CHOICES = (
    (DOCUMENT_TYPE_AUXILIARY, AUXILIARY_DOCUMENT),
    (DOCUMENT_TYPE_REFERENCE, REFERENCE_DOCUMENT),
    (DOCUMENT_TYPE_UNKNOWN, UNKNOWN.title()),
)

CLASSIFICATION_DOMAIN_GENERAL = 'general'
CLASSIFICATION_DOMAIN_FINANCE = 'finance'
CLASSIFICATION_DOMAIN_INSURANCE = 'insurance'
TAG_DOMAINS = (
    CLASSIFICATION_DOMAIN_FINANCE,
    CLASSIFICATION_DOMAIN_GENERAL,
)
CLASSIFICATION_DOMAIN_CHOICES = (
    (CLASSIFICATION_DOMAIN_GENERAL, CLASSIFICATION_DOMAIN_GENERAL.title()),
    (CLASSIFICATION_DOMAIN_FINANCE, CLASSIFICATION_DOMAIN_FINANCE.title()),
    (CLASSIFICATION_DOMAIN_INSURANCE, CLASSIFICATION_DOMAIN_INSURANCE.title()),
)

DOCUMENT_ASSOCIATION_PURPOSE_UNKNOWN = UNKNOWN
DOCUMENT_ASSOCIATION_PURPOSE_QUESTION = 'question'
DOCUMENT_ASSOCIATION_PURPOSE_HYPOTHESIS = 'hypothesis'
DOCUMENT_ASSOCIATION_PURPOSES = (
    DOCUMENT_ASSOCIATION_PURPOSE_HYPOTHESIS,
    DOCUMENT_ASSOCIATION_PURPOSE_QUESTION,
    DOCUMENT_ASSOCIATION_PURPOSE_UNKNOWN
)
DOCUMENT_ASSOCIATION_PURPOSE_CHOICES = (
    (DOCUMENT_ASSOCIATION_PURPOSE_HYPOTHESIS, DOCUMENT_ASSOCIATION_PURPOSE_HYPOTHESIS.title()),
    (DOCUMENT_ASSOCIATION_PURPOSE_QUESTION, DOCUMENT_ASSOCIATION_PURPOSE_QUESTION.title()),
    (DOCUMENT_ASSOCIATION_PURPOSE_UNKNOWN, DOCUMENT_ASSOCIATION_PURPOSE_UNKNOWN.title())
)
