# Generated by Django 2.2.3 on 2019-08-05 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ondalear.backend.core.django.fields
import ondalear.backend.core.django.storage
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('target', models.CharField(choices=[('aux', 'Auxiliary Document'), ('ref', 'Reference Document')], default='ref', max_length=1024)),
                ('domain', models.CharField(choices=[('gen', 'General'), ('fin', 'Finance'), ('ins', 'Insurance')], default='gen', max_length=1024)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'ondalear_docmgmt_category',
                'get_latest_by': 'update_time',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('client_id', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=256)),
                ('is_system', models.BooleanField(default=False)),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_client_related_creation_user', to=settings.AUTH_USER_MODEL)),
                ('effective_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_client_related_effective_user', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_client_related_site', to='sites.Site')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_client_related_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'ondalear_docmgmt_client',
                'get_latest_by': 'update_time',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('language', models.CharField(default='en-us', max_length=1024)),
                ('mime_type', models.CharField(choices=[('text/plain', 'Plain Text'), ('application/octet-stream', 'Unknown')], default='application/octet-stream', max_length=1024)),
                ('document_type', models.CharField(choices=[('aux', 'Auxiliary Document'), ('ref', 'Reference Document'), ('unknown', 'Unknown')], default='ref', max_length=1024)),
                ('title', models.CharField(blank=True, max_length=256, null=True)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='docmgmt.Category')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Client')),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_document_related_creation_user', to=settings.AUTH_USER_MODEL)),
                ('effective_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_document_related_effective_user', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_document_related_site', to='sites.Site')),
            ],
            options={
                'verbose_name': 'Document',
                'verbose_name_plural': 'Documents',
                'db_table': 'ondalear_docmgmt_document',
                'get_latest_by': 'update_time',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AuxiliaryDocument',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='docmgmt.Document')),
                ('content', models.TextField(blank=True, max_length=1048576, null=True)),
                ('upload', ondalear.backend.core.django.fields.MimeTypeConstrainedFileField(blank=True, content_types=('text/plain',), max_upload_size=10485760, mime_lookup_length=4096, null=True, storage=ondalear.backend.core.django.storage.OverwriteStorage(), unique=True, upload_to=ondalear.backend.core.django.storage.client_directory_path)),
                ('dir_path', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name': 'Auxiliary document',
                'verbose_name_plural': 'Auxiliary documents',
                'db_table': 'ondalear_docmgmt_auxiliary_document',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ReferenceDocument',
            fields=[
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='docmgmt.Document')),
                ('content', models.TextField(blank=True, max_length=1048576, null=True)),
                ('upload', ondalear.backend.core.django.fields.MimeTypeConstrainedFileField(blank=True, content_types=('text/plain',), max_upload_size=10485760, mime_lookup_length=4096, null=True, storage=ondalear.backend.core.django.storage.OverwriteStorage(), unique=True, upload_to=ondalear.backend.core.django.storage.client_directory_path)),
                ('dir_path', models.CharField(blank=True, max_length=2048, null=True)),
            ],
            options={
                'verbose_name': 'Reference document',
                'verbose_name_plural': 'Reference documents',
                'db_table': 'ondalear_docmgmt_reference_document',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(blank=True, max_length=2048, null=True)),
                ('target', models.CharField(choices=[('aux', 'Auxiliary Document'), ('ref', 'Reference Document')], default='ref', max_length=1024)),
                ('domain', models.CharField(choices=[('gen', 'General'), ('fin', 'Finance'), ('ins', 'Insurance')], default='gen', max_length=1024)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Client')),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_tag_related_creation_user', to=settings.AUTH_USER_MODEL)),
                ('effective_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_tag_related_effective_user', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='docmgmt.Tag')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_tag_related_site', to='sites.Site')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_tag_related_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tag',
                'verbose_name_plural': 'Tags',
                'db_table': 'ondalear_docmgmt_tag',
                'get_latest_by': 'update_time',
                'abstract': False,
                'unique_together': {('client', 'name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='DocumentTag',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Client')),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documenttag_related_creation_user', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Document')),
                ('effective_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documenttag_related_effective_user', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documenttag_related_site', to='sites.Site')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Tag')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documenttag_related_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document tag',
                'verbose_name_plural': 'Document tags',
                'db_table': 'ondalear_docmgmt_document_tag',
                'get_latest_by': 'update_time',
                'abstract': False,
                'unique_together': {('document', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='tags',
            field=models.ManyToManyField(related_name='documents', through='docmgmt.DocumentTag', to='docmgmt.Tag'),
        ),
        migrations.AddField(
            model_name='document',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_document_related_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ClientUser',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('has_logged_in', models.BooleanField(default=False)),
                ('login_count', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Client')),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_clientuser_related_creation_user', to=settings.AUTH_USER_MODEL)),
                ('effective_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_clientuser_related_effective_user', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_clientuser_related_site', to='sites.Site')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_clientuser_related_update_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Client user',
                'verbose_name_plural': 'Client users',
                'db_table': 'ondalear_docmgmt_client_user',
                'get_latest_by': 'update_time',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Client'),
        ),
        migrations.AddField(
            model_name='category',
            name='creation_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_category_related_creation_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='effective_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_category_related_effective_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='docmgmt.Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_category_related_site', to='sites.Site'),
        ),
        migrations.AddField(
            model_name='category',
            name='update_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_category_related_update_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('client', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('client', 'name', 'parent')},
        ),
    ]
