# Generated by Django 2.2.3 on 2019-08-07 18:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('docmgmt', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('annotation', models.TextField(max_length=4096)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Client')),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_annotation_related_creation_user', to=settings.AUTH_USER_MODEL)),
                ('effective_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_annotation_related_effective_user', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_annotation_related_site', to='sites.Site')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_annotation_related_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Annotation',
                'verbose_name_plural': 'Annotations',
                'db_table': 'ondalear_docmgmt_annotation',
                'get_latest_by': 'update_time',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentAnnotation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('annotation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Annotation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Client')),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documentannotation_related_creation_user', to=settings.AUTH_USER_MODEL)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Document')),
                ('effective_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documentannotation_related_effective_user', to=settings.AUTH_USER_MODEL)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documentannotation_related_site', to='sites.Site')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documentannotation_related_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document annotation',
                'verbose_name_plural': 'Document annotations',
                'db_table': 'ondalear_docmgmt_document_annotation',
                'get_latest_by': 'update_time',
                'abstract': False,
                'unique_together': {('document', 'annotation')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='annotations',
            field=models.ManyToManyField(related_name='documents', through='docmgmt.DocumentAnnotation', to='docmgmt.Annotation'),
        ),
    ]
