# Generated by Django 2.2.3 on 2019-08-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docmgmt', '0004_annotation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annotation',
            name='name',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='annotation',
            unique_together={('client', 'name')},
        ),
    ]
