# Generated by Django 2.2.3 on 2019-08-07 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docmgmt', '0005_required_annotation_name'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('client', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('client', 'name')},
        ),
    ]
