# Generated by Django 2.2.3 on 2019-08-08 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('docmgmt', '0006_nonunique_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='has_logged_in',
        ),
    ]
