# Generated by Django 2.2.3 on 2019-08-16 21:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sites', '0002_alter_domain_unique'),
        ('docmgmt', '0008_remove_client_login_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='domain',
            field=models.CharField(choices=[('general', 'General'), ('finance', 'Finance'), ('insurance', 'Insurance')], default='general', max_length=1024),
        ),
        migrations.AlterField(
            model_name='category',
            name='target',
            field=models.CharField(choices=[('auxiliary', 'Auxiliary Document'), ('reference', 'Reference Document')], default='reference', max_length=1024),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('auxiliary', 'Auxiliary Document'), ('reference', 'Reference Document'), ('unknown', 'Unknown')], default='reference', max_length=1024),
        ),
        migrations.AlterField(
            model_name='tag',
            name='domain',
            field=models.CharField(choices=[('general', 'General'), ('finance', 'Finance'), ('insurance', 'Insurance')], default='general', max_length=1024),
        ),
        migrations.AlterField(
            model_name='tag',
            name='target',
            field=models.CharField(choices=[('auxiliary', 'Auxiliary Document'), ('reference', 'Reference Document')], default='reference', max_length=1024),
        ),
        migrations.CreateModel(
            name='DocumentAssociation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('version', models.IntegerField(default=0)),
                ('is_enabled', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('purpose', models.CharField(choices=[('hypothesis', 'Hypothesis'), ('question', 'Question'), ('unknown', 'Unknown')], default='unknown', max_length=1024)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='docmgmt.Client')),
                ('creation_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documentassociation_related_creation_user', to=settings.AUTH_USER_MODEL)),
                ('effective_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documentassociation_related_effective_user', to=settings.AUTH_USER_MODEL)),
                ('from_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_document', to='docmgmt.Document')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documentassociation_related_site', to='sites.Site')),
                ('to_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_document', to='docmgmt.Document')),
                ('update_user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='docmgmt_documentassociation_related_update_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Document association',
                'verbose_name_plural': 'Document associations',
                'db_table': 'ondalear_docmgmt_document_association',
                'get_latest_by': 'update_time',
                'abstract': False,
                'unique_together': {('from_document', 'to_document', 'purpose')},
            },
        ),
        migrations.AddField(
            model_name='document',
            name='documents',
            field=models.ManyToManyField(related_name='related_documents', through='docmgmt.DocumentAssociation', to='docmgmt.Document'),
        ),
    ]
