# Generated by Django 2.2.3 on 2019-08-17 21:35

from django.db import migrations
import ondalear.backend.core.django.fields
import ondalear.backend.core.django.storage


class Migration(migrations.Migration):

    dependencies = [
        ('docmgmt', '0009_document_association'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auxiliarydocument',
            name='upload',
            field=ondalear.backend.core.django.fields.MimeTypeConstrainedFileField(blank=True, content_types=('text/plain',), max_upload_size=10485760, mime_lookup_length=4096, null=True, storage=ondalear.backend.core.django.storage.OverwriteStorage(), upload_to=ondalear.backend.core.django.storage.client_directory_path),
        ),
        migrations.AlterField(
            model_name='referencedocument',
            name='upload',
            field=ondalear.backend.core.django.fields.MimeTypeConstrainedFileField(blank=True, content_types=('text/plain',), max_upload_size=10485760, mime_lookup_length=4096, null=True, storage=ondalear.backend.core.django.storage.OverwriteStorage(), upload_to=ondalear.backend.core.django.storage.client_directory_path),
        ),
    ]
