"""
.. module:: ondalear.backend.settings
   :synopsis: django top level settings module

Django settings for document project.

Generated by 'django-admin startproject' using Django 2.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""
# pylint: disable=wildcard-import,unused-wildcard-import
from ondalear.backend.config.common.root import (CURRENT_ENV, DEV_ENV,
                                                 LOCAL_ENV, STAGING_ENV, PROD_ENV)


if CURRENT_ENV in (DEV_ENV, LOCAL_ENV):
    from ondalear.backend.config.dev import *
elif CURRENT_ENV == STAGING_ENV:
    # @TODO define staging env
    pass
elif CURRENT_ENV == PROD_ENV:
    # @TODO define prod env
    pass
else:
    raise ValueError('Invalid environment %s' % CURRENT_ENV)

try:
    from .settings_local import *
except ImportError:
    pass
